osx_image: xcode7.3
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install xcpretty cocoapods --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild -workspace Example/TYMActivityIndicatorView.xcworkspace -scheme TYMActivityIndicatorView-Example -sdk iphonesimulator -destination "platform=iOS Simulator,OS=9.1,name=iPhone 6s" ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
